### ISSUE TITLE
zk-task

### ISSUE THREAD

**Issue by etch1n9** [swanchain/devgrants#1]

**Comment by iany8034** [comment]
zk-task

RAM: 16GB
STORAGE:250GB

**Comment by PatrickVintage20** [comment]
Goodday to the swan community  , my name is patrickvintage and I am a data scientist,  I will be delighted to be a part of your team success through my skill on data science I do really wish my proposal is granted 

Thank you

**Comment by flyworker** [comment]
> Goodday to the swan community , my name is patrickvintage and I am a data scientist, I will be delighted to be a part of your team success through my skill on data science I do really wish my proposal is granted
> 
> Thank you

Hi @PatrickVintage20  I think you should use "new issue" to create a proposal instead reply to this thread.

**Comment by PatrickVintage20** [comment]
@flyworker so sorry about it   I have done it as you instructed

**Comment by flyworker** [comment]
Not a grant application
