### ISSUE TITLE
Swan DevGrant<Power Voting>

### ISSUE THREAD

**Issue by xianglinhe** [swanchain/devgrants#15]
# Open Grant Proposal: `Power Voting`

**Project Name:**`Power Voting`.

**Proposal Category:** `Applications`.

**Individual or Entity Name:** `Black Domain DAO`.

**Proposer:** `xianglinhe`.

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** `Yes`.

# Project Summary

Swan is a leading provider of cross-chain cloud computing solutions.

Power Voting utilizes Drand TimeLock technology to achieve fair and private voting. Before the voting deadline, no one’s voting results will be seen by others, and the voting process will not be disturbed by other participant’s voting results. After the voting deadline, anyone can count the votes in a decentralized manner, and the results of the counting will executed and stored by smart contract and will not be manipulated by any centralized organization or individual.

Power Voting aims to become the infrastructure of DAO governance on Swan chain.

## Impact

1. Solved the problem of lacking a native DAO governance tool on Swan Chain.
2. Solved the problem of existing voting DAO governance tools on the market that do not allow various roles such as Swan's developers, storage providers, stakers, and others to participate in the voting governance.
3. Bring more fairness and efficiency to community governance for Swan.

## Outcomes

The project will include three parts:

1. Utilizes Drand TimeLock technology to achieve fair and private voting. Before the voting deadline, no one’s voting results will be seen by others, and the voting process will not be disturbed by other participant’s voting results.
2. Uses UCAN delegation to proxy the accounts of various roles such as developers, stakers, storage providers, token holders, etc., to the Swan chain accounts, in order to represent these accounts in contract voting operations on the Swan chain.
3. Uses a decentralized Power Oracle to obtain the weights of various roles such as developers, stakers, storage providers, token holders, etc., and converting them into standardized voting weights, which are then stored on the Swan chain for use by the power voting contract.

## Adoption, Reach, and Growth Strategies

A DAO community is typically composed of various roles, but common community governance tools often limit voting participation to token holders only. Power Voting enables fair and private participation in community governance voting for roles such as developers, stakers, storage providers, and token holders. It allows the community to evolve towards greater decentralization and democracy. Power Voting aims to become the infrastructure for DAO governance on Swan chain.

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
| --- | --- | --- | --- | --- |
| Milestone1 | Implement UCAN delegation to allow accounts of various roles such as developers, stakers, storage providers, and more to vote on contracts on the Swan chain. | UCAN delegation generation and verification tools. | 2 Weeks | 10,000 SWAN |
| Milestone2 | Implement Power Oracle nodes and contracts to obtain the weights of various roles such as developers, stakers, storage providers, token holders, and more. Then convert the weights into standardized voting weights and store them on Swan chain. | Power Oracle node and contracts. | 6 Weeks | 30,000 SWAN |
| Milestone3 | Integrate UCAN delegation, power oracle, and Drand TimeLock into Power Voting to implement the voting features. | Power Voting frontend, backend and contracts. | 1 Week | 10,000 SWAN |

## Maintenance and Upgrade Plans

**Maintenance**: Perform routine maintenance to ensure the stable and reliable operation of the Power Voting project. This includes bug fixing and performance optimization.

**Documentation**: Provide comprehensive documentation covering design diagrams, application usage, FAQ compilation, and efficient support for developers and users.

# Team

## Team Members

Albert: System Architect

Will: Software Engineer

Kennes: Software Engineer

## Relevant Experience

Power voting has been deployed on Filecoin chain, providing the Filecoin ecosystem with a privacy-preserving and fair community voting governance tool that allows participation from various roles such as token holders, clients, SPs, developers, and more. This is achieved through technologies such as Drand TimeLock, UCAN delegation, decentralized power oracles, and others. 

Power voting has received a grant from the Filecoin Foundation and will be used as a voting governance tool by the foundation in the future.

## Team code repositories

[https://github.com/black-domain](https://github.com/black-domain)

# Additional Information

gmail: xianglinhe@gmail.com

**Comment by JL289** [comment]
Hello there @xianglinhe, 

We'd like to know more about the project, could you please provide more information pertaining to:

- your and your teams development experience? Can't seem to find too much relevant information to confirm abilities.

- Marketing and Distribution plans for your application? No plans were provided that we can see.

Sorry for the wait, let us know if you have any questions!

Cheers,

**Comment by joekingss** [comment]
Hi  @JL289,

Our team possesses extensive development experience in the Filecoin, IPFS, and Ethereum ecosystems.

Albert, our architect, has many years of experience in dApp architecture design. He has a rich background in front-end, back-end, and smart contract development, coupled with extensive expertise in contract security audits. You can view his GitHub profile here: https://github.com/hexianglinss

Will, our front-end engineer, is highly skilled in dApp front-end development, Chrome extension development, and Flutter app development. He is proficient in React, NextJS, IndexedDB, Flutter, Wagmi, WebPack, and other technologies. His GitHub profile is available here: https://github.com/willpan1102

Kennes, our back-end development engineer, brings a wealth of experience in back-end development and blockchain data analysis. He is highly proficient in go-eth, The Graph, Kubernetes, and various databases. You can find his GitHub profile here: https://github.com/liuzeming1

Our plan is to undertake in-depth development based on Swan's features to support voting for different roles, such as developers, stakers, storage providers, and token holders. We aim to collaborate with Swan to become its official voting tool, similar to our successful project with Filecoin.

Thanks!

**Comment by JL289** [comment]
Thank you for your response @hexianglinss 

We will review this information and get back to you shortly. 

Cheers,

**Comment by CryptoSenorita** [comment]
Hi Power Voting team,

Thank you so much for your time and effort in preparing this proposal, and for your patience throughout our review process. We truly appreciate the work you've put in, and we recognize that some time has passed since your original submission.

After careful consideration, we regret to inform you that we are unable to proceed with a grant at this time. However, we remain excited to see the progress of your project and wish you every success as you continue to build and grow.

Wishing you all the best,
Swan Chain Team
