### ISSUE TITLE
Swan DevGrant < Link the Resource Providers of Storage（Filecoin）and Computing（Swan）>

### ISSUE THREAD

**Issue by GenomicBank** [swanchain/devgrants#19]
# Open Grant Proposal: `Link the Resource Providers of Storage（Filecoin）and Computing（Swan）`

Link the Resource Providers  of Storage（**F**ilecoin）and Computing（**S**wan）

**Project Name:**

**LinkFS**

**Proposal Category:** Choose one of `Developer and data tooling`, `Applications`, `Integrations`, `Research & protocols`, `Other`. 

**D**eveloper and data tooling

**Individual or Entity Name:** Is the proposal on behalf of an individual, or an entity/organization? Please note that the agreement and any payments must be completed by the same entity, either individual or organization.

**Yi Gong Technology** (Guangzhou) Limited Liability Company

**Proposer:** `replace with your GitHub username`

https://github.com/GenomicBank

**(Optional) Swan ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Swan or Lagrange, and any others.` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the Swan or Lagrange project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No".

**Y**es

# Project Summary

The essence of the decentralized storage ecosystem is to reduce the cost of user storage needs through decentralized storage services. The lower the cost of the storage ecosystem, the stronger its competitiveness and the better its development. Generally speaking, in the decentralized storage ecosystem, Filecoin primarily aims to reduce the storage hardware and its operational costs through a storage network, while Swan is mainly used to reduce the computational hardware and operational costs. In addition, reducing data size through data compression to significantly lower data storage costs and operational costs is also a very important method to promote the development of the ecosystem, especially for complex large-scale data such as genomic sequencing data and marine simulation data. These types of data often amount to petabytes and grow rapidly. Effectively reducing storage costs through efficient compression algorithms is a very promising entrepreneurial direction to promote the decentralized storage ecosystem.

This project is dedicated to designing compression algorithms for complex large-scale data, utilizing the SWAN computing power network to effectively execute the compression algorithms to compress the data within the Filecoin storage network. Subsequently, data is stored with storage service providers through the Filecoin storage network, ultimately achieving a significant reduction in storage costs and promoting the development of both the SWAN computing power network and the Filecoin storage network, thereby fostering the growth of the decentralized storage ecosystem.

## Impact 

- **S**ignificantly reduce the cost of decentralized storage, enhance the competitiveness of the ecosystem, and prosper the SWAN computing power network and Filecoin storage network.

## Outcomes
We can discuss face to face. 

## Adoption, Reach, and Growth Strategies
We can discuss face to face. 

## Development Roadmap

We can discuss face to face. 

## Total Budget Requested

#Milestone: **ZeroToOne** 
#Description & Deliverables : **Design** & Implement the compression API between storage providers and swan computing provider 
#Completion Date: **5/1, 2024**
#Funding: **5000 dollars**

## Maintenance and Upgrade Plans

We can discuss face to face. 

# Team

## Team Members

https://github.com/GenomicBank

## Team Website
https://github.com/GenomicBank

## Relevant Experience

   1. **F**innish my Bachelor, Master, and Ph.D. study in Computer Science and Technology from a 985 university, and graduated within three years from the undergraduate program（10 out of 6500+ students）, with a strong background in computer development.
   2. **P**ossesses ten years of experience in the design and implementation of compression algorithms, and has published multiple papers as the first author in top-tier journals and conferences in the field of compression.
   3. **A**s an individual participant, attempted to enter and successfully reached the finals of a million-scale compression algorithm competition.
   4. **A**s an individual participant, tried out for the MiraclePlus Innovation Forum and was granted an interview opportunity with Dr. Qi Lu (top 5%).

## Team code repositories
https://github.com/GenomicBank

# Additional Information

**1183771097@qq.com**

**Comment by JL289** [comment]
Hello there @GenomicBank,

We'd like to know more about the project, could you please provide more information pertaining to: 

- Your and your teams development experience? Can't seem to find relevant experience. 
- Marketing and Distribution plans for your application? No plan was provided. Mention needing to discuss face to face? 
- Note that grant allocations will be in token, so please let us know how much SWAN you would want for this project.

Sorry for the wait, let us know if you have any questions! 

Cheers,

**Comment by JL289** [comment]
Hello @GenomicBank, 

Could you please provide the required information? 

Thanks,

**Comment by CryptoSenorita** [comment]
Hi Link the Resource Providers of Storage（Filecoin）and Computing（Swan） team,

Thank you so much for your time and effort in preparing this proposal, and for your patience throughout our review process. We truly appreciate the work you've put in, and we recognize that some time has passed since your original submission.

After careful consideration, we regret to inform you that we are unable to proceed with a grant at this time. However, we remain excited to see the progress of your project and wish you every success as you continue to build and grow.

Wishing you all the best,
Swan Chain Team
