### ISSUE TITLE
Swan DevGrant<Proxima Testnet>

### ISSUE THREAD

**Issue by bq1024** [swanchain/devgrants#5]
# Open Grant Proposal: Build Swan Chain Testnet Proxima

**Project Name:** `Proxima Testnet`

**Proposal Category:** `Research & protocols`

**Individual or Entity Name:** `Nebula Block Team`

**Proposer:** `@bq1024`

**(Optional) Swan ecosystem affiliations:** `One of the largest computing providers for Lagrange` 

**(Optional) Technical Sponsor:** `@flyworker `

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** `Yes`

# Project Summary

## Impact 

**Problem Statement**:
The current Swan Chain lacks and robust testnet. Developers face challenges in simulating real-world scenarios and validating the functionality, security, and scalability of the Swan Chain. To address these issues, we propose the development of a comprehensive testnet named Proxima.

**Project Description**:
The Proxima testnet aims to provide a realistic and scalable environment for Swan Chain developers to test and validate their work. The project will involve the following key components:
- Network Simulation: Implementing a realistic simulation of the Swan Chain network to mimic real-world conditions, ensuring accurate testing of various use cases.
- Smart Contract Testing: Creating a dedicated environment for testing and validating smart contracts, allowing developers to identify and address issues before deployment to the mainnet.
- Security Auditing: Conducting thorough security audits within the testnet environment to proactively identify and address potential vulnerabilities, enhancing the overall security of the Swan Chain platform.
- Scalability Testing: Assessing the scalability of Swan Chain by simulating a large number of nodes and transactions to identify performance bottlenecks and optimize resource utilization.

## Outcomes

- **Proxima Testnet Environment**: A fully functional, dedicated testnet environment named Proxima for Swan Chain.

- **Testnet Monitoring and Analytics**: Integration of monitoring and analytics tools within the Proxima testnet to provide real-time insights into network performance, smart contract execution, and overall system health.

- **Documentation**: Comprehensive documentation detailing the Proxima testnet architecture and guidelines for developers to effectively utilize the testnet for their testing and development activities.

- **Developer Resources and Support**: Provision of developer resources, including guides, tutorials, and support channels, to assist Swan Chain developers in effectively using the Proxima testnet. This includes ongoing support for addressing queries and issues related to the testnet.

## Adoption, Reach, and Growth Strategies

The target audience for the Proxima Testnet Development project for Swan Chain includes:

- Swan Chain Developers: Developers working on Swan Chain projects who require a reliable and realistic testnet environment for testing and validating their applications.
- Computing Providers: Computing Providers (CPs) that support Swan Chain's ecosystem.
- Communities: The broader community associated with Swan Chain, including users, enthusiasts, and contributors.

### Milestone 1: Proxima Testnet Environment Setup
**Functionality**:
- Basic infrastructure for the Proxima testnet established.
- Initial network simulation and configuration.

**Team and Roles**:
- 1 field engineer for servers setup and configuration.
- 3 blockchain developers for Proxima testnet setup and configuration.
- 1 front-end developer for Proxima explorer development.

**Funding**:
- $30,000 for infrastructure, tools, and initial development.

**Timeframe**:
- Estimated completion within 2 months.

### Milestone 2: Enhanced Testnet Features and Documentation
**Functionality**:
- Expanded network simulation to mimic real-world scenarios.
- Comprehensive documentation for developers.

**Team and Roles**:
- 2 developers for enhancing network simulation.
- 1 technical writer for documentation.

**Funding**:
- $10,000 for infrastructure, tools, and initial development.

**Timeframe**:
- Estimated completion within 1 months.

### Milestone 3: Security Audits and Vulnerability Fixes
**Functionality**:
- Implementation of security audit processes.
- Identification and resolution of vulnerabilities within the Proxima testnet.

**Team and Roles**:
- 2 developers for conducting audits.
- 1 developer for implementing fixes.

**Funding**:
- $10,000 for security audits, tools, and fixes.

**Timeframe**:
- Estimated completion within 1 months.

### Milestone 4: Optimization
**Functionality**:
- Optimization of the Proxima testnet for increased performance.

**Team and Roles**:
- 1 developers for optimization and monitoring.

**Funding**:
- $5,000 for optimization efforts and monitoring.

**Timeframe**:
- Estimated completion within 1 months.

## Total Budget Requested

$55,000

## Maintenance and Upgrade Plans

- **Regular Updates and Feature Enhancements**: Schedule regular updates to the Proxima testnet, incorporating new features, optimizations, and improvements based on user feedback and evolving technological requirements.
- **Community Engagement and Support**: Maintain active engagement with the Swan Chain community through forums, social media, and other channels. Provide ongoing support, address user queries.
- **Documentation Updates**: Keep the documentation up-to-date with the latest features and changes in the Proxima testnet. Ensure that developers have access to comprehensive and accurate information.

# Team

## Team Members

Boqian Wang: Director of Engineering
Genevieve Lin Rui: Business Development Executive
Mike Li: Network architect & Fullstack
Yiming Liang: Field Engineer

## Team Member LinkedIn Profiles

Boqian Wang: https://www.linkedin.com/in/boqian-wang-6b0955171/
Genevieve Lin Rui: https://www.linkedin.com/in/genevieve-lin-rui-4927961a/
Mike Li: https://www.linkedin.com/in/mike-li-a8b86a188/
Yiming Liang: https://www.linkedin.com/in/yiming-liang-93091518b/

## Team Website

https://www.nebulablock.com/

## Team code repositories

https://github.com/Nebula-Block-Data

# Additional Information

**Comment by CryptoSenorita** [comment]
Hi Proxima Testnet team,

Thank you so much for your time and effort in preparing this proposal, and for your patience throughout our review process. We truly appreciate the work you've put in, and we recognize that some time has passed since your original submission.

After careful consideration, we regret to inform you that we are unable to proceed with a grant at this time. However, we remain excited to see the progress of your project and wish you every success as you continue to build and grow.

Wishing you all the best,
Swan Chain Team
