### ISSUE TITLE
ZK-Task Information

### ISSUE THREAD

**Issue by PhenVentures** [swanchain/devgrants#8]
Implementing a customized binary for secure data processing.

Resource Requirements:
RAM: 16GB
Storage: 200GB
vCPU numbers: 4
GPU: Nvidia GTX 1080
Input Parameters: JSON file with task specifications.
Task Completion: Utilize the provided binary for data processing.
Output: ZK proof generated after task completion.
Verification: Refer to the attached verification guide.
Additional Parameters: Any additional information, requirements, or dependencies.
A complete example: Include the task sample, proof, verify result etc.

**Comment by flyworker** [comment]
closed as irrelevant
