### ISSUE TITLE
Swan DevGrant<ALEO-ZK-UBI>

### ISSUE THREAD

**Issue by aleoweb123** [swanchain/devgrants#9]
# Open Grant Proposal: `Add Aleo Prover proof to the swan zk market`

**Project Name:**`ALEO-ZK-UBI`.

**Proposal Category:** `Applications`. 

**Individual or Entity Name:** `SoterHQ`.

**Proposer:** `SoterHQ`.

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** `Yes`.

# Project Summary

Swan Chain offers a platform where these compute-intensive tasks can be outsourced to a global network of computing providers, incentivized by the prospect of earning through the platform's Universal Basic Income (UBI) model.
aleo-zk-ubi is a ZK market implementation built on the Swan Chain. It allows Prover in the Aleo network to submit the zk-proof task (Puzzle Solution) to the Swan Network. Computing Providers (CPs) in the Swan Network can earn corresponding UBI rewards by completing these tasks.

## Impact 

1. Lack of efficient utilization of resources: The project aims to utilize resources effectively by allowing Provers in the Aleo network to offload zk proof generation tasks to the Swan Network, potentially reducing redundancy and optimizing resource allocation.
2. Incentive misalignment: By offering UBI rewards to Computing Providers (CPs) for completing tasks, the project seeks to align incentives within the ecosystem, encouraging participation and contribution.
3. Increased participation: Offering UBI rewards can attract more CPs to participate in the ecosystem, fostering collaboration and engagement.

## Outcomes

The project will include three part:

1. Integrate `aleo_prover_for_swanchain`
2. Integrate `ubi-pool-contracts`
3. Integrate `professional-grade AleoProver software`

## Adoption, Reach, and Growth Strategies

`aleo-zk-ubi` is a tool designed to assist computing power providers. These providers are the primary contributors to the Swan Network, offering a significant amount of computational power. Within the Aleo blockchain, the `Aleo Prover proof` plays a crucial role that requires substantial computing capabilities. To address this, `aleo-zk-ubi` delegates the computation tasks of the `Aleo Prover proof` to the computing power providers of the Swan Network. This approach offers several benefits. Firstly, completing the delegated computing tasks for the Aleo Prover allows the computing power providers of the Swan Network to earn greater profits. This, in turn, attracts more Aleo miners to participate in the Swan Network, thereby increasing their potential earnings. Secondly, this delegation of computing tasks enhances the security of the Swan Network.

## Total Budget Requested

| Milestone # | Description                                                  | Deliverables                                                 | Completion Date | Funding |
| ----------- | ------------------------------------------------------------ | ------------------------------------------------------------ | --------------- | ------- |
| Milestone1  | Design and implement the AleoProver software based on the UBI protocol of Swanchain. | aleo_prover_for_swanchain                          | 2 Weeks             | 200,000  SWAN |
| Milestone2  | Design and implement smart contracts for computing power verification and settlement. | Deploy and run the smart contracts.            | 6 Weeks            | 200,000  SWAN |
| Milestone3  | Design and implement a solution to allow third-party AleoProver software to access Swanchain. | Ensure compatibility of one or more AleoProver software with Swanchain. | 1 Week             | 100,000 SWAN |

## Maintenance and Upgrade Plans

**Maintenance**: Perform routine maintenance to ensure the stable and reliable operation of the aleo-zk-ubi project. This includes bug fixing and performance optimization.

**Ecosystem**: Open-source the AleoProver integration specifications and assist third-party software in participating in Swan Chain. Actively drive improvements to the integration process.

**Documentation**: Provide comprehensive documentation covering application usage, proof software integration, FAQ compilation, and efficient support for developers and users.

# Team

## Team Members

David: System Architect

Marlin: Software Engineer

## Team Member LinkedIn Profiles

David [Github Profiles](https://github.com/aleoweb123)

Marlin [Github Profiles](https://github.com/soterhq)

## Team Website

https://sotertech.io/

## Relevant Experience

SoterHQ is a cutting-edge technology company committed to advancing the fundamental components of Web3 infrastructure and delivering top-tier technical services. Our headquarters are located in Singapore, with dedicated research and development centers established in Shanghai and Wuhan, China. At SoterHQ, we possess proprietary core algorithms and technologies in key Web3 domains, including Decentralized Storage, Decentralized Networking, Privacy Computing. We are proud to offer comprehensive cross-platform technology solutions.

## Team code repositories

https://github.com/soterhq

# Additional Information

**Comment by flyworker** [comment]
From my understanding this project offers a way to outsourcing Aleo ZK task to swan network, can CP on swan network get computing reward from Aelo? or it is more like a free service vendor to Aleo?

**Comment by aleoweb123** [comment]
> From my understanding this project offers a way to outsourcing Aleo ZK task to swan network, can CP on swan network get computing reward from Aelo? or it is more like a free service vendor to Aleo?

In this module, there are two roles: client and CPS (Compute Provider Service).
The client submits a computation task, and the CPS executes the computation task.
The client pays with UBI, and the CPS receives UBI (not Aleo tokens).

**Comment by JL289** [comment]
Hello there @aleoweb123,  

We'd like to know more about the project, could you please provide more information pertaining to:

- your and your teams development experience? Not much information to go on based on available information provided.

- Marketing and Distribution plans for your application? We see no information provided besides reaching out to Aleo miners.

Sorry for the wait, let us know if you have any questions!

Cheers,

**Comment by aleoweb123** [comment]
> Hello there @aleoweb123,
> 
> We'd like to know more about the project, could you please provide more information pertaining to:
> 
> * your and your teams development experience? Not much information to go on based on available information provided.
> * Marketing and Distribution plans for your application? We see no information provided besides reaching out to Aleo miners.
> 
> Sorry for the wait, let us know if you have any questions!
> 
> Cheers,

We have extensive experience in ZK system and application development. In the Aleo ecosystem, our team has been continuously developing tools and applications. We have much experience in Aleo prover implementation and optimization.

Acutally we have optimized the low level algorithm of Aleo prover a lot, which is necessary for fast Aleo miners. We can give you more details later. This work connects ALEO and SWAN with an efficient way. We believe it will be very useful for the ecosystems.

**Comment by JL289** [comment]
Hey @aleoweb123, 

Would it be possible to be more precise with the information provided? Also, you haven't provided information with regards to marketing and distribution. Thank you for sharing more information here.

**Comment by CryptoSenorita** [comment]
Hi ALEO-ZK-UBI team,

Thank you so much for your time and effort in preparing this proposal, and for your patience throughout our review process. We truly appreciate the work you've put in, and we recognize that some time has passed since your original submission.

After careful consideration, we regret to inform you that we are unable to proceed with a grant at this time. However, we remain excited to see the progress of your project and wish you every success as you continue to build and grow.

Wishing you all the best,
Swan Chain Team
